apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-configmap
  namespace: bank
data:
  MYSQL_DATABASE: bankappdb
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankappdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
