apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-deployment
  namespace: bank
  labels:
    app: bankapp
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  serviceName: mysql
  replicas: 2
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
          - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bank-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: bank-configmap
              key: MYSQL_DATABASE
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: mysql
      labels:
        app: bankapp
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi

