kind: Service
apiVersion: v1
metadata:
  name: bank-svc
  namespace: bank
  labels:
    app: app
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8081
      nodePort: 30080
