kind: Deployment
apiVersion: apps/v1
metadata:
  name: bank-deployment
  namespace: bank
  labels:
    app: bankapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bank-pod
        image: swayamnakshane/bank
        ports:
          - containerPort: 8080
     

        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bank-secret
              key: SPRING_DATASOURCE_PASSWORD

        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: bank-configmap
              key: SPRING_DATASOURCE_USERNAME

        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: bank-configmap
              key: SPRING_DATASOURCE_URL


#        livenessProbe:
#           httpGet:
#             path: /actuator/health
#             port: 8080
#           initialDelaySeconds: 10 
#            periodSeconds: 5          
#            failureThreshold: 3
#
#        readinessProbe:
#            httpGet:
#              path: /actuator/health   
#              port: 8080
#            initialDelaySeconds: 5    
#            periodSeconds: 5        
#            failureThreshold: 3

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
