apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: bank
  labels:
    app: bankapp

spec:
  clusterIP: None
  selector:
    app: bankapp
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

