kind: PersistentVolume
apiVersion: v1
metadata:
  name: bank-pvc
  namespace: bank
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostsPath:
    path: '/tmp/bankapp-msql'
