kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bank-pvc
  namespace: bank
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
