apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bank-pvc
  namespace: bank
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
