kind: PersistentVolume
apiVersion: v1
metadata:
  name: bank-pv
  namespace: bank
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/mnt/data"



