apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: bank
  labels:
    app: bankapp
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"

